/** Clinical Cartography: inventory operations retain the exact route names and data shapes of the inventory and consumption services. */
import { apiRequest, isDemoMode } from "./api";
import { alerts, drugs } from "./mockData";

export const inventoryService = {
  async listDrugs(filters: { category?: string; search?: string } = {}) { if (isDemoMode) return drugs.filter((drug) => (!filters.category || filters.category === "All" || drug.category === filters.category) && (!filters.search || drug.name.toLowerCase().includes(filters.search.toLowerCase()))); return apiRequest<{ data: unknown[] }>("inventory", "/drugs", { params: { category: filters.category === "All" ? undefined : filters.category, limit: 100 } }).then((result) => result.data); },
  async getDrug(id: string) { if (isDemoMode) return drugs.find((drug) => drug.id === id) ?? null; return apiRequest<unknown>("inventory", `/drugs/${id}`); },
  async listBatches(drugId?: string) { if (isDemoMode) return drugs.find((drug) => drug.id === drugId)?.batches ?? []; return apiRequest<{ data: unknown[] }>("inventory", "/batches", { params: { drug_id: drugId, limit: 100 } }).then((result) => result.data); },
  async getFacilityStock(facilityId: string, lowStockOnly?: boolean) { if (isDemoMode) return drugs.map(({ id, name, currentStock, nearestExpiry }) => ({ drug_id: id, drug_name: name, quantity_on_hand: currentStock, expiry_date: nearestExpiry })); return apiRequest<unknown[]>("inventory", `/facilities/${facilityId}/stock`, { params: { low_stock_only: lowStockOnly } }); },
  async listAlerts(filters: { type?: string; severity?: string; status?: string } = {}) { if (isDemoMode) return alerts.filter((alert) => (!filters.type || filters.type === "All" || alert.type === filters.type) && (!filters.severity || filters.severity === "All" || alert.severity === filters.severity) && (!filters.status || filters.status === "All" || alert.state === filters.status)); return apiRequest<{ data: unknown[] }>("inventory", "/alerts", { params: { type: filters.type === "All" ? undefined : filters.type, severity: filters.severity === "All" ? undefined : filters.severity, status: filters.status === "All" ? undefined : filters.status, limit: 100 } }).then((result) => result.data); },
  async updateAlertStatus(id: string, status: "acknowledged" | "resolved") { if (isDemoMode) { const alert = alerts.find((item) => item.id === id); if (alert) alert.state = status === "resolved" ? "Resolved" : "Acknowledged"; return alert; } return apiRequest("inventory", `/alerts/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }); },
};
