/** Clinical Cartography: realistic operational records give the interface a coherent India-scale demo story while retaining backend-ready field names. */
export const facilities = [
  { id: "fac-msmw", name: "Maharashtra State Medical Warehouse", code: "MH-STATE-001", type: "State Warehouse", availability: 97, criticalDrugs: 0, inbound: 12, risk: "Low", x: -2.1, y: 1.0, z: 0 },
  { id: "fac-mumbai", name: "Mumbai District Hospital", code: "MH-DH-024", type: "District Hospital", availability: 86, criticalDrugs: 3, inbound: 2, risk: "Elevated", x: 0.0, y: -0.45, z: 0.2 },
  { id: "fac-pune", name: "Pune Regional Medical Center", code: "MH-RMC-014", type: "Regional Medical Center", availability: 94, criticalDrugs: 0, inbound: 4, risk: "Low", x: 1.75, y: -1.05, z: -0.15 },
  { id: "fac-nashik", name: "Nashik District Hospital", code: "MH-DH-018", type: "District Hospital", availability: 91, criticalDrugs: 1, inbound: 1, risk: "Watch", x: 1.15, y: 0.95, z: 0.35 },
  { id: "fac-thane", name: "Thane Medical College", code: "MH-MC-011", type: "Medical College", availability: 98, criticalDrugs: 0, inbound: 3, risk: "Low", x: -1.25, y: -1.3, z: -0.1 },
];

export const drugs = [
  { id: "drug-para", name: "Paracetamol 500mg", category: "Analgesic", currentStock: 1840, unit: "tablets", batchCount: 4, nearestExpiry: "18 Sep 2026", expiryDays: 31, storage: "15–25°C", fefo: "High priority", health: "critical", trend: -18, manufacturer: "Cipla Health", sku: "PCM-500-TAB", reorderLevel: 2200, stockPercent: 38, batches: [{ batchNo: "PCM-MH-24091", manufacturer: "Cipla Health", manufacturingDate: "19 Sep 2024", expiryDate: "18 Sep 2026", quantity: 740, status: "Critical" }, { batchNo: "PCM-MH-24128", manufacturer: "Cipla Health", manufacturingDate: "02 Nov 2024", expiryDate: "01 Nov 2026", quantity: 1100, status: "Available" }], movements: [{ date: "Today, 09:40", type: "Consumption", quantity: "− 460 tablets", reference: "Mumbai District Hospital" }, { date: "Yesterday, 17:22", type: "Transfer in", quantity: "+ 900 tablets", reference: "MH-STATE-001" }] },
  { id: "drug-amox", name: "Amoxicillin 500mg", category: "Antibiotic", currentStock: 12450, unit: "capsules", batchCount: 7, nearestExpiry: "14 Dec 2026", expiryDays: 118, storage: "15–25°C", fefo: "Standard", health: "healthy", trend: 6, manufacturer: "Apex Pharmaceuticals", sku: "AMX-500-CAP", reorderLevel: 6000, stockPercent: 87, batches: [{ batchNo: "AMX-25-117", manufacturer: "Apex Pharmaceuticals", manufacturingDate: "15 Dec 2024", expiryDate: "14 Dec 2026", quantity: 2450, status: "Available" }, { batchNo: "AMX-25-213", manufacturer: "Apex Pharmaceuticals", manufacturingDate: "10 Mar 2025", expiryDate: "09 Mar 2027", quantity: 10000, status: "Available" }], movements: [{ date: "Today, 07:15", type: "Receipt", quantity: "+ 2,400 capsules", reference: "SH-MH-20481" }, { date: "14 Aug, 11:02", type: "Consumption", quantity: "− 620 capsules", reference: "Mumbai District Hospital" }] },
  { id: "drug-insulin", name: "Insulin Glargine", category: "Endocrinology", currentStock: 320, unit: "pens", batchCount: 2, nearestExpiry: "27 Aug 2026", expiryDays: 9, storage: "2–8°C", fefo: "Immediate priority", health: "critical", trend: -22, manufacturer: "NovoCare India", sku: "IG-100-3ML", reorderLevel: 650, stockPercent: 24, batches: [{ batchNo: "IG-MH-332", manufacturer: "NovoCare India", manufacturingDate: "28 Aug 2024", expiryDate: "27 Aug 2026", quantity: 180, status: "Near expiry" }, { batchNo: "IG-MH-341", manufacturer: "NovoCare India", manufacturingDate: "11 Oct 2024", expiryDate: "10 Oct 2026", quantity: 140, status: "Available" }], movements: [{ date: "Today, 08:05", type: "Consumption", quantity: "− 72 pens", reference: "Mumbai District Hospital" }, { date: "13 Aug, 14:38", type: "Transfer out", quantity: "− 50 pens", reference: "Nashik District Hospital" }] },
  { id: "drug-cef", name: "Ceftriaxone 1g", category: "Antibiotic", currentStock: 5280, unit: "vials", batchCount: 4, nearestExpiry: "12 Feb 2027", expiryDays: 178, storage: "15–25°C", fefo: "Standard", health: "healthy", trend: 4, manufacturer: "Zydus Lifesciences", sku: "CEF-1G-VIAL", reorderLevel: 3000, stockPercent: 76, batches: [{ batchNo: "CEF-26-019", manufacturer: "Zydus Lifesciences", manufacturingDate: "13 Feb 2025", expiryDate: "12 Feb 2027", quantity: 2850, status: "Available" }], movements: [{ date: "15 Aug, 08:21", type: "Receipt", quantity: "+ 1,280 vials", reference: "SH-MH-20321" }] },
  { id: "drug-ors", name: "ORS Sachets", category: "Fluid Therapy", currentStock: 18760, unit: "sachets", batchCount: 9, nearestExpiry: "20 Nov 2026", expiryDays: 94, storage: "Below 30°C", fefo: "Standard", health: "healthy", trend: 12, manufacturer: "HealthFirst Labs", sku: "ORS-20-SACH", reorderLevel: 9000, stockPercent: 93, batches: [{ batchNo: "ORS-0706", manufacturer: "HealthFirst Labs", manufacturingDate: "21 Nov 2024", expiryDate: "20 Nov 2026", quantity: 5500, status: "Available" }], movements: [{ date: "Today, 06:30", type: "Transfer in", quantity: "+ 3,000 sachets", reference: "MH-STATE-001" }] },
  { id: "drug-azi", name: "Azithromycin 250mg", category: "Antibiotic", currentStock: 2710, unit: "tablets", batchCount: 3, nearestExpiry: "02 Oct 2026", expiryDays: 45, storage: "15–25°C", fefo: "High priority", health: "warning", trend: -7, manufacturer: "Sunwell Pharma", sku: "AZI-250-TAB", reorderLevel: 2500, stockPercent: 54, batches: [{ batchNo: "AZI-191", manufacturer: "Sunwell Pharma", manufacturingDate: "03 Oct 2024", expiryDate: "02 Oct 2026", quantity: 1210, status: "High priority" }], movements: [{ date: "Today, 10:15", type: "Consumption", quantity: "− 350 tablets", reference: "Pune Regional Medical Center" }] },
];

export const dashboardSnapshot = {
  metrics: [
    { label: "Medicine availability", value: 97.2, suffix: "%", detail: "+0.8% vs. last week", tone: "blue" },
    { label: "Critical shortages", value: 8, suffix: "", detail: "3 require intervention today", tone: "critical" },
    { label: "Near expiry batches", value: 24, suffix: "", detail: "9 within 30 days", tone: "warning" },
    { label: "Active shipments", value: 17, suffix: "", detail: "2 due within 24 hours", tone: "blue" },
    { label: "Network facilities", value: 126, suffix: "", detail: "118 reporting normally", tone: "healthy" },
  ],
  availability: { overall: 97.2, states: [{ label: "Within threshold", value: 118, color: "#16803c" }, { label: "Watch", value: 5, color: "#b7791f" }, { label: "Critical", value: 3, color: "#c53030" }] },
  consumptionTrend: [
    { day: "Mon", observed: 67, forecast: 64 }, { day: "Tue", observed: 72, forecast: 68 }, { day: "Wed", observed: 66, forecast: 68 }, { day: "Thu", observed: 80, forecast: 73 }, { day: "Fri", observed: 75, forecast: 76 }, { day: "Sat", observed: 86, forecast: 79 }, { day: "Sun", observed: 81, forecast: 83 },
  ],
  operationalAlerts: [
    { id: "alert-para", severity: "critical", drug: "Paracetamol 500mg", facility: "Mumbai District Hospital", message: "Stockout predicted within 2 days.", action: "Review drug" },
    { id: "alert-insulin", severity: "warning", drug: "Insulin Glargine", facility: "Mumbai District Hospital", message: "180 pens reach expiry in 9 days.", action: "Review batch" },
    { id: "alert-shipment", severity: "warning", drug: "Ceftriaxone 1g", facility: "Nashik District Hospital", message: "Shipment SH-MH-20476 is 6 hours behind ETA.", action: "View shipment" },
  ],
  activity: [
    { time: "09:40", action: "Consumption recorded", detail: "460 Paracetamol tablets at Mumbai District Hospital", kind: "consumption" },
    { time: "08:05", action: "Threshold crossed", detail: "Insulin Glargine moved to critical level", kind: "alert" },
    { time: "07:15", action: "Shipment received", detail: "2,400 Amoxicillin capsules entered state warehouse stock", kind: "receipt" },
    { time: "06:30", action: "Transfer dispatched", detail: "3,000 ORS sachets en route to Thane Medical College", kind: "transfer" },
  ],
};

export const procurement = {
  indents: [
    { id: "IND-MH-0821", facility: "Mumbai District Hospital", drug: "Paracetamol 500mg", quantity: 8500, priority: "Emergency", status: "Pending approval", raised: "Today, 08:18", expected: "21 Aug 2026" },
    { id: "IND-MH-0816", facility: "Nashik District Hospital", drug: "Ceftriaxone 1g", quantity: 1200, priority: "Urgent", status: "Approved", raised: "18 Aug 2026", expected: "23 Aug 2026" },
    { id: "IND-MH-0809", facility: "Pune Regional Medical Center", drug: "Azithromycin 250mg", quantity: 4000, priority: "Normal", status: "Ordered", raised: "17 Aug 2026", expected: "26 Aug 2026" },
    { id: "IND-MH-0798", facility: "Thane Medical College", drug: "ORS Sachets", quantity: 14000, priority: "Normal", status: "Completed", raised: "14 Aug 2026", expected: "18 Aug 2026" },
  ],
  orders: [
    { id: "SO-MH-3418", drug: "Ceftriaxone 1g", vendor: "Zydus Lifesciences", quantity: 1200, status: "Confirmed", origin: "Maharashtra State Medical Warehouse", destination: "Nashik District Hospital", expected: "23 Aug 2026", shipment: "SH-MH-20476" },
    { id: "SO-MH-3412", drug: "Paracetamol 500mg", vendor: "Cipla Health", quantity: 8500, status: "Created", origin: "Maharashtra State Medical Warehouse", destination: "Mumbai District Hospital", expected: "21 Aug 2026", shipment: "Not dispatched" },
    { id: "SO-MH-3397", drug: "Azithromycin 250mg", vendor: "Sunwell Pharma", quantity: 4000, status: "Confirmed", origin: "Maharashtra State Medical Warehouse", destination: "Pune Regional Medical Center", expected: "26 Aug 2026", shipment: "SH-MH-20463" },
  ],
};

export const shipments = [
  { id: "ship-cef", trackingNumber: "SH-MH-20476", supplyOrder: "SO-MH-3418", vendor: "Zydus Lifesciences", drug: "Ceftriaxone 1g", quantity: "1,200 vials", origin: "Maharashtra State Medical Warehouse", destination: "Nashik District Hospital", status: "In transit", eta: "Today, 18:30", progress: 62, delay: "6h later than planned", events: [{ status: "Requirement approved", location: "Nashik District Hospital", occurred: "18 Aug, 09:10", complete: true }, { status: "Packed", location: "Maharashtra State Medical Warehouse", occurred: "19 Aug, 06:20", complete: true }, { status: "Dispatched", location: "Mumbai distribution hub", occurred: "19 Aug, 07:05", complete: true }, { status: "Transit", location: "Kasara Ghat checkpoint", occurred: "19 Aug, 11:40", complete: true, current: true }, { status: "Delivered", location: "Nashik District Hospital", occurred: "Estimated 18:30", complete: false }, { status: "Received", location: "Nashik District Hospital", occurred: "Awaiting receipt", complete: false }] },
  { id: "ship-ors", trackingNumber: "SH-MH-20481", supplyOrder: "SO-MH-3404", vendor: "HealthFirst Labs", drug: "ORS Sachets", quantity: "3,000 sachets", origin: "Maharashtra State Medical Warehouse", destination: "Thane Medical College", status: "Dispatched", eta: "Today, 15:10", progress: 42, delay: "On schedule", events: [{ status: "Requirement approved", location: "Thane Medical College", occurred: "18 Aug, 13:00", complete: true }, { status: "Packed", location: "Maharashtra State Medical Warehouse", occurred: "19 Aug, 05:45", complete: true }, { status: "Dispatched", location: "Mumbai distribution hub", occurred: "19 Aug, 06:30", complete: true, current: true }, { status: "Transit", location: "Thane corridor", occurred: "Expected 12:30", complete: false }, { status: "Delivered", location: "Thane Medical College", occurred: "Estimated 15:10", complete: false }, { status: "Received", location: "Thane Medical College", occurred: "Awaiting receipt", complete: false }] },
  { id: "ship-amox", trackingNumber: "SH-MH-20463", supplyOrder: "SO-MH-3397", vendor: "Apex Pharmaceuticals", drug: "Amoxicillin 500mg", quantity: "4,000 capsules", origin: "Maharashtra State Medical Warehouse", destination: "Pune Regional Medical Center", status: "Delivered", eta: "Received 18 Aug", progress: 100, delay: "Received as planned", events: [{ status: "Requirement approved", location: "Pune Regional Medical Center", occurred: "15 Aug, 11:10", complete: true }, { status: "Packed", location: "Maharashtra State Medical Warehouse", occurred: "16 Aug, 08:10", complete: true }, { status: "Dispatched", location: "Mumbai distribution hub", occurred: "16 Aug, 09:05", complete: true }, { status: "Transit", location: "Pune highway corridor", occurred: "17 Aug, 07:20", complete: true }, { status: "Delivered", location: "Pune Regional Medical Center", occurred: "18 Aug, 10:25", complete: true }, { status: "Received", location: "Pune Regional Medical Center", occurred: "18 Aug, 11:02", complete: true, current: true }] },
];

export const alerts = [
  { id: "alert-1", severity: "Critical", state: "Open", type: "Stockout", drug: "Paracetamol 500mg", facility: "Mumbai District Hospital", message: "Stockout predicted within 2 days based on recent consumption.", time: "38 minutes ago", recommendation: "Prioritize SO-MH-3412 and transfer 1,100 tablets from MH-STATE-001." },
  { id: "alert-2", severity: "Critical", state: "Open", type: "Low stock", drug: "Insulin Glargine", facility: "Mumbai District Hospital", message: "Available stock is below the configured 7-day cover threshold.", time: "2 hours ago", recommendation: "Transfer 320 pens from Pune Regional Medical Center." },
  { id: "alert-3", severity: "Warning", state: "Acknowledged", type: "Near expiry", drug: "Insulin Glargine", facility: "Mumbai District Hospital", message: "180 pens from batch IG-MH-332 expire in 9 days.", time: "3 hours ago", recommendation: "Issue this batch first and assess transfer to a higher-consumption site." },
  { id: "alert-4", severity: "Warning", state: "Open", type: "Delayed shipment", drug: "Ceftriaxone 1g", facility: "Nashik District Hospital", message: "SH-MH-20476 is projected to arrive 6 hours behind planned ETA.", time: "4 hours ago", recommendation: "Confirm receiving dock readiness and alert the pharmacy lead." },
  { id: "alert-5", severity: "Info", state: "Open", type: "Abnormal consumption", drug: "ORS Sachets", facility: "Thane Medical College", message: "Consumption is 31% above the four-week baseline.", time: "Yesterday", recommendation: "Monitor trend for 48 hours before escalating replenishment." },
  { id: "alert-6", severity: "Warning", state: "Resolved", type: "Low stock", drug: "Azithromycin 250mg", facility: "Pune Regional Medical Center", message: "Stock threshold was breached, then restored by transfer TR-MH-1162.", time: "Yesterday", recommendation: "Resolution recorded." },
];

export const insights = [
  { id: "insight-1", type: "Shortage risk", title: "Shortage risk detected", drug: "Insulin Glargine", facility: "Mumbai District Hospital", metric: "4 days", metricLabel: "Projected stockout", confidence: 92, explanation: "Daily use rose 22% against the four-week average while available stock remained below the 7-day cover threshold.", action: "Transfer 320 pens from Pune Regional Medical Center.", status: "Immediate action" },
  { id: "insight-2", type: "Redistribution", title: "Redistribution opportunity", drug: "Paracetamol 500mg", facility: "Mumbai District Hospital", metric: "1,100 units", metricLabel: "Recommended transfer", confidence: 89, explanation: "State warehouse batch PCM-MH-24128 has sufficient cover and can reduce the expected shortage window before new supply arrives.", action: "Approve transfer TR-MH-1178 from MH-STATE-001.", status: "Recommended" },
  { id: "insight-3", type: "Expiry optimization", title: "FEFO action is required", drug: "Insulin Glargine", facility: "Mumbai District Hospital", metric: "9 days", metricLabel: "To nearest expiry", confidence: 96, explanation: "Batch IG-MH-332 contains 180 pens nearing expiry and matches current ward demand.", action: "Prioritize batch IG-MH-332 for all eligible dispensing.", status: "Operational action" },
  { id: "insight-4", type: "Demand forecast", title: "Demand expected to normalize", drug: "ORS Sachets", facility: "Thane Medical College", metric: "+14%", metricLabel: "7-day forecast", confidence: 78, explanation: "A seasonal uplift is expected to remain above baseline but does not currently require emergency procurement.", action: "Maintain a 14-day safety stock and observe consumption daily.", status: "Monitor" },
];

export const network = { nodes: facilities, edges: [["fac-msmw", "fac-mumbai"], ["fac-msmw", "fac-pune"], ["fac-msmw", "fac-nashik"], ["fac-msmw", "fac-thane"], ["fac-mumbai", "fac-thane"]] as [string, string][] };

