/** Clinical Cartography: the dashboard prioritizes availability, attention-worthy exceptions, and the active route network over a wall of statistics. */
import { lazy, Suspense, useEffect, useState } from "react";
import { useLocation } from "wouter";
import { Activity, ArrowRight, Boxes, BrainCircuit, ChevronRight, CircleAlert, Network, PackageCheck, Route, Truck, X } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeader, SectionHeading, StatusBadge } from "@/components/OperationalPrimitives";
import { InlineError, PanelSkeleton } from "@/components/OperationalStates";
import { apiConfigLabel, isDemoMode } from "@/services/api";
import { dashboardSnapshot } from "@/services/mockData";
import { useOperationData } from "@/hooks/useOperationData";

const SupplyChainScene = lazy(() => import("@/components/SupplyChainScene"));

function AnimatedNumber({ value, suffix }: { value: number; suffix?: string }) {
  const [display, setDisplay] = useState(0);
  useEffect(() => { let frame = 0; const start = performance.now(); const duration = 550; const tick = (now: number) => { const ratio = Math.min((now - start) / duration, 1); setDisplay(value * (1 - Math.pow(1 - ratio, 3))); if (ratio < 1) frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [value]);
  return <span className="data-number">{Number.isInteger(value) ? Math.round(display) : display.toFixed(1)}{suffix}</span>;
}

export default function Dashboard() {
  const [, navigate] = useLocation();
  const { data, loading, error, retry } = useOperationData(async () => dashboardSnapshot, []);
  const [networkOpen, setNetworkOpen] = useState(false);
  if (loading) return <div className="page-enter"><PanelSkeleton className="mb-5" lines={2} /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{Array.from({ length: 5 }).map((_, index) => <PanelSkeleton key={index} lines={2} />)}</div></div>;
  if (error || !data) return <InlineError message={error ?? undefined} retry={retry} />;
  return <div className="page-enter max-w-[1640px]">
    <PageHeader eyebrow="National operations" title="Operations overview" subtitle="Medicine availability and supply activity across the Maharashtra network." action={<div className={`inline-flex items-center gap-2 rounded border px-3 py-2 text-[11px] font-bold uppercase tracking-[0.08em] ${isDemoMode ? "border-sky-200 bg-sky-50 text-[#0f5d9f]" : "border-emerald-200 bg-emerald-50 text-[#16803c]"}`}><span className={`h-1.5 w-1.5 rounded-full ${isDemoMode ? "bg-[#2196d2]" : "bg-[#16803c]"}`} />{apiConfigLabel()}</div>} />
    <section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5" aria-label="Key performance indicators">
      {data.metrics.map((metric) => <article key={metric.label} className="surface-panel surface-panel-hover min-h-[126px] p-4"><p className="label-kicker">{metric.label}</p><div className="mt-3 flex items-end justify-between gap-2"><p className={`data-number text-[28px] font-bold tracking-[-0.045em] ${metric.tone === "critical" ? "text-[#c53030]" : metric.tone === "warning" ? "text-[#a96810]" : metric.tone === "healthy" ? "text-[#16803c]" : "text-[#0b4f88]"}`}><AnimatedNumber value={metric.value} suffix={metric.suffix} /></p><span className={`mb-1 h-2 w-2 rounded-full ${metric.tone === "critical" ? "bg-[#c53030]" : metric.tone === "warning" ? "bg-[#b7791f]" : metric.tone === "healthy" ? "bg-[#16803c]" : "bg-[#2196d2]"}`} /></div><p className="mt-2 border-t border-[#e7f0f5] pt-2 text-[11px] font-medium text-[#64748b]">{metric.detail}</p></article>)}
    </section>
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(330px,.65fr)]">
      <article className="surface-panel p-5 sm:p-6"><SectionHeading label="Consumption signal" title="Seven-day medicine consumption" detail="Observed volume compared with demand baseline, in thousands of units." action={<button onClick={() => navigate("/insights")} className="hidden items-center gap-1 text-xs font-bold text-[#1769aa] hover:text-[#0b4f88] sm:flex">View forecast <ArrowRight size={14} /></button>} /><div className="mt-5 h-[270px] sm:h-[300px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.consumptionTrend} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><defs><linearGradient id="observedFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2196d2" stopOpacity={0.25} /><stop offset="100%" stopColor="#2196d2" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e5eef4" strokeDasharray="3 4" /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: "#71879a", fontSize: 11 }} dy={8} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#71879a", fontSize: 10 }} tickFormatter={(value) => `${value}k`} /><Tooltip cursor={{ stroke: "#9bcde5", strokeWidth: 1 }} contentStyle={{ border: "1px solid #dce8f0", borderRadius: "6px", boxShadow: "0 10px 20px rgba(11,31,51,0.1)", fontSize: 12 }} labelStyle={{ color: "#102a43", fontWeight: 700 }} /><Area type="monotone" dataKey="forecast" stroke="#8da7b8" strokeWidth={1.5} strokeDasharray="4 4" fill="none" name="Baseline" /><Area type="monotone" dataKey="observed" stroke="#1769aa" strokeWidth={2.4} fill="url(#observedFill)" name="Observed" /></AreaChart></ResponsiveContainer></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 border-t border-[#e7f0f5] pt-3 text-[11px] font-medium text-[#64748b]"><span className="inline-flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-[#1769aa]" />Observed consumption</span><span className="inline-flex items-center gap-2"><i className="h-px w-3 border-t-2 border-dashed border-[#8da7b8]" />Demand baseline</span><span className="ml-auto text-[#426076]">Daily refresh · 06:00 IST</span></div></article>
      <article className="surface-panel overflow-hidden"><div className="border-b border-[#dce8f0] p-5 sm:p-6"><SectionHeading label="Attention queue" title="Operational alerts" detail="Items needing action or verification." action={<button onClick={() => navigate("/alerts")} className="text-xs font-bold text-[#1769aa] hover:text-[#0b4f88]">View all</button>} /></div><div>{data.operationalAlerts.map((alert, index) => <button key={alert.id} onClick={() => navigate(alert.id === "alert-shipment" ? "/shipments" : alert.id === "alert-para" ? "/inventory" : "/alerts")} className={`group w-full px-5 py-4 text-left hover:bg-[#f8fcfe] sm:px-6 ${index > 0 ? "border-t border-[#e7f0f5]" : ""}`}><div className="flex items-start gap-3"><span className={`mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded border ${alert.severity === "critical" ? "border-red-200 bg-red-50 text-[#c53030]" : "border-amber-200 bg-amber-50 text-[#a96810]"}`}><CircleAlert size={15} /></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><StatusBadge status={alert.severity} label={alert.severity === "critical" ? "Critical" : "Warning"} /><span className="text-[12px] font-bold text-[#102a43]">{alert.drug}</span></span><span className="mt-1.5 block text-[11px] font-medium text-[#557084]">{alert.facility}</span><span className="mt-1 block text-xs text-[#64748b]">{alert.message}</span><span className="mt-2 inline-flex items-center gap-1 text-[11px] font-bold text-[#1769aa] group-hover:text-[#0b4f88]">{alert.action} <ChevronRight size={13} /></span></span></div></button>)}</div><button onClick={() => navigate("/alerts")} className="flex w-full items-center justify-center gap-2 border-t border-[#dce8f0] bg-[#f8fcfe] py-3 text-xs font-bold text-[#1769aa] hover:bg-[#eaf5fc]"><Activity size={14} />Open alert worklist</button></article>
    </section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.12fr)_minmax(310px,.88fr)]">
      <article className="relative min-h-[270px] overflow-hidden rounded-[10px] border border-[#0b4f88] bg-[#0b3659] p-5 text-white sm:p-6"><img src="/manus-storage/distrack-shipment-route_53ac9077.jpg" alt="Medicine shipment route between distribution facility and district hospital" className="absolute inset-0 h-full w-full object-cover opacity-75" /><div className="absolute inset-0 bg-gradient-to-r from-[#09263f]/95 via-[#09263f]/74 to-[#09263f]/18" /><div className="relative flex h-full flex-col"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-sky-200">Route in focus</p><h2 className="mt-2 text-xl font-bold tracking-[-0.025em]">Ceftriaxone delivery is in transit</h2></div><StatusBadge status="warning" label="6h delayed" className="border-amber-300/40 bg-amber-50 text-[#7a4a0a]" /></div><p className="mt-3 max-w-md text-sm leading-6 text-slate-200">SH-MH-20476 is carrying 1,200 vials from the state warehouse to Nashik District Hospital.</p><div className="mt-auto flex flex-wrap items-center gap-x-6 gap-y-2 border-t border-white/20 pt-4 text-[11px] font-medium text-slate-200"><span><span className="text-sky-200">Current location</span><br />Kasara Ghat checkpoint</span><span><span className="text-sky-200">Revised ETA</span><br />Today, 18:30</span><button onClick={() => navigate("/shipments")} className="ml-auto inline-flex h-9 items-center gap-2 rounded border border-white/30 bg-white/10 px-3 text-xs font-bold text-white hover:bg-white/20">Track shipment <ArrowRight size={14} /></button></div></div></article>
      <article className="surface-panel relative overflow-hidden p-5 sm:p-6"><img src="/manus-storage/distrack-analytics-texture_c2d2cd15.jpg" alt="" className="pointer-events-none absolute inset-0 h-full w-full object-cover opacity-[0.16]" /><div className="relative"><SectionHeading label="Decision support" title="Redistribution action recommended" detail="Highest confidence operational recommendation." /><div className="mt-5 flex items-start justify-between gap-5"><div><p className="text-[13px] font-bold text-[#102a43]">Insulin Glargine</p><p className="mt-1 text-xs text-[#64748b]">Mumbai District Hospital</p></div><div className="text-right"><p className="data-number text-2xl font-bold tracking-[-0.04em] text-[#0b4f88]">92%</p><p className="label-kicker mt-1">Confidence</p></div></div><p className="mt-4 border-l-2 border-[#2196d2] pl-3 text-[13px] leading-5 text-[#426076]">Transfer 320 pens from Pune Regional Medical Center to protect four days of projected service.</p><button onClick={() => navigate("/insights")} className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-[#1769aa] hover:text-[#0b4f88]">Review recommendation <ArrowRight size={14} /></button></div></article>
    </section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.12fr)_minmax(310px,.88fr)]">
      <article className="surface-panel overflow-hidden"><div className="flex items-center justify-between border-b border-[#dce8f0] p-5 sm:p-6"><div><p className="label-kicker">Network visibility</p><h2 className="mt-1.5 text-[15px] font-bold text-[#102a43]">Maharashtra supply network</h2></div><button onClick={() => setNetworkOpen(true)} className="inline-flex h-9 items-center gap-2 rounded-md border border-[#b9d4e5] bg-white px-3 text-xs font-bold text-[#1769aa] hover:bg-[#eaf5fc]"><Network size={15} />Explore network</button></div><div className="relative min-h-[190px] overflow-hidden"><img src="/manus-storage/distrack-national-network_c8046537.jpg" alt="Abstract regional medicine supply network map" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-white/95 via-white/65 to-transparent" /><div className="relative max-w-[370px] p-5 sm:p-6"><p className="text-[13px] font-bold text-[#102a43]">118 facilities are currently within threshold.</p><p className="mt-2 text-xs leading-5 text-[#557084]">Three facilities require direct coordination. Route activity is concentrated between Mumbai, Nashik, and Pune this afternoon.</p><div className="mt-5 flex h-2 overflow-hidden rounded-full bg-[#e4edf3]">{data.availability.states.map((state) => <span key={state.label} style={{ width: `${(state.value / 126) * 100}%`, backgroundColor: state.color }} />)}</div><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-[10px] font-semibold text-[#4a657a]">{data.availability.states.map((state) => <span key={state.label}>{state.value} {state.label.toLowerCase()}</span>)}</div></div></div></article>
      <article className="surface-panel overflow-hidden"><div className="flex items-center justify-between border-b border-[#dce8f0] p-5 sm:p-6"><div><p className="label-kicker">Live ledger</p><h2 className="mt-1.5 text-[15px] font-bold text-[#102a43]">Network activity</h2></div><button onClick={() => navigate("/audit")} className="text-xs font-bold text-[#1769aa] hover:text-[#0b4f88]">Audit trail</button></div><div>{data.activity.map((item, index) => <div key={`${item.time}-${item.action}`} className={`flex gap-3 px-5 py-3.5 sm:px-6 ${index ? "border-t border-[#edf3f6]" : ""}`}><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${item.kind === "alert" ? "bg-[#c53030]" : item.kind === "receipt" ? "bg-[#16803c]" : item.kind === "transfer" ? "bg-[#1769aa]" : "bg-[#2196d2]"}`} /><div className="min-w-0 flex-1"><div className="flex items-baseline justify-between gap-3"><p className="text-[12px] font-bold text-[#102a43]">{item.action}</p><time className="data-number whitespace-nowrap text-[10px] font-medium text-[#7b92a4]">{item.time}</time></div><p className="mt-1 text-[11px] leading-4 text-[#64748b]">{item.detail}</p></div></div>)}</div></article>
    </section>
    {networkOpen && <div className="fixed inset-0 z-50 bg-[#071827]/45 p-3 backdrop-blur-[2px] sm:p-8"><div className="mx-auto flex h-full max-w-6xl flex-col overflow-auto rounded-xl border border-[#c7dce9] bg-[#f9fcfe] shadow-2xl"><header className="flex items-start justify-between border-b border-[#dce8f0] bg-white px-5 py-5 sm:px-7"><div><p className="label-kicker">Interactive visualization</p><h2 className="mt-2 text-xl font-bold tracking-[-0.025em] text-[#0b1f33]">State to facility supply network</h2><p className="mt-1 text-sm text-[#64748b]">Select a facility node to review its current availability and shortage exposure.</p></div><button onClick={() => setNetworkOpen(false)} aria-label="Close network visualization" className="grid h-9 w-9 place-items-center rounded-md border border-[#dce8f0] text-[#64748b] hover:bg-[#f2f8fc]"><X size={18} /></button></header><div className="flex-1 p-4 sm:p-7"><Suspense fallback={<PanelSkeleton className="h-full" lines={5} />}><SupplyChainScene /></Suspense></div></div></div>}
  </div>;
}
