/** Clinical Cartography: shipment tracking is an event route, showing what has happened, where responsibility now sits, and what comes next. */
import { useState } from "react";
import { Clock3, MapPin, PackageCheck, Route, Truck, XCircle } from "lucide-react";
import { toast } from "sonner";
import { DetailDrawer } from "@/components/DetailDrawer";
import { InlineError, PanelSkeleton } from "@/components/OperationalStates";
import { PageHeader, SectionHeading, StatusBadge } from "@/components/OperationalPrimitives";
import { ShipmentTimeline } from "@/components/ShipmentTimeline";
import { useOperationData } from "@/hooks/useOperationData";
import { shipmentService } from "@/services/shipmentService";
import { shipments } from "@/services/mockData";

type Shipment = (typeof shipments)[number];
function shipmentTone(status: string) { return status === "Delivered" ? "resolved" : status === "In transit" ? "warning" : "active"; }

export default function Shipments() {
  const [filter, setFilter] = useState("All");
  const [selected, setSelected] = useState<Shipment | null>(null);
  const { data, loading, error, retry } = useOperationData(async () => (await shipmentService.listShipments(filter)) as Shipment[], [filter]);
  const receive = async (shipment: Shipment) => { await shipmentService.updateShipmentStatus(shipment.id, "Received", shipment.destination, "Receipt confirmed by facility operations."); toast.success("Shipment receipt confirmed.", { description: `${shipment.trackingNumber} has been added to the receiving ledger.` }); await retry(); setSelected(null); };
  if (loading && !data) return <div className="page-enter"><PanelSkeleton lines={2} /><div className="mt-5"><PanelSkeleton lines={6} /></div></div>;
  if (error) return <InlineError message={error} retry={retry} />;
  return <div className="page-enter max-w-[1640px]">
    <PageHeader eyebrow="Operations / Shipments" title="Shipment visibility" subtitle="Follow every procurement delivery from requirement approval through confirmed receipt." action={<button onClick={() => toast.message("Shipment creation is initiated from a confirmed supply order.")} className="inline-flex h-10 items-center gap-2 rounded-md border border-[#b9d4e5] bg-white px-3.5 text-xs font-bold text-[#1769aa] hover:bg-[#eaf5fc]"><PackageCheck size={16} />Receive a delivery</button>} />
    <section className="mb-5 grid gap-3 md:grid-cols-3"><article className="surface-panel p-4"><p className="label-kicker">In motion</p><p className="data-number mt-2 text-2xl font-bold text-[#0b4f88]">2</p><p className="mt-1 text-xs text-[#64748b]">Shipments on active routes</p></article><article className="surface-panel p-4"><p className="label-kicker">ETA within 24h</p><p className="data-number mt-2 text-2xl font-bold text-[#a96810]">2</p><p className="mt-1 text-xs text-[#64748b]">One is behind plan</p></article><article className="surface-panel p-4"><p className="label-kicker">Received this week</p><p className="data-number mt-2 text-2xl font-bold text-[#16803c]">14</p><p className="mt-1 text-xs text-[#64748b]">Across monitored facilities</p></article></section>
    <section className="surface-panel route-ledger overflow-hidden"><div className="flex flex-col gap-4 border-b border-[#dce8f0] p-4 sm:p-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="label-kicker">Route register</p><h2 className="mt-1.5 text-[15px] font-bold text-[#102a43]">Active and recent shipments</h2></div><div className="flex gap-2 overflow-x-auto">{["All", "In transit", "Dispatched", "Delivered"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`h-8 whitespace-nowrap rounded-md border px-3 text-[11px] font-bold ${filter === item ? "border-[#1769aa] bg-[#eaf5fc] text-[#0f5d9f]" : "border-[#dce8f0] text-[#64748b] hover:bg-[#f6fafd]"}`}>{item}</button>)}</div></div><div className="divide-y divide-[#edf3f6]">{(data ?? []).map((shipment) => <button key={shipment.id} onClick={() => setSelected(shipment)} className="group grid w-full gap-3 px-5 py-4 text-left hover:bg-[#fbfdfe] sm:grid-cols-[minmax(0,1.1fr)_minmax(185px,.95fr)_minmax(180px,.9fr)_auto] sm:items-center sm:gap-5 sm:px-6"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-mono text-[11px] font-bold text-[#0b4f88]">{shipment.trackingNumber}</p><StatusBadge status={shipmentTone(shipment.status)} label={shipment.status} /></div><p className="mt-1.5 text-[13px] font-bold text-[#102a43]">{shipment.drug}</p><p className="mt-1 text-[11px] text-[#71879a]">{shipment.quantity} · {shipment.vendor}</p></div><div className="hidden min-w-0 sm:block"><p className="label-kicker">Delivery route</p><p className="mt-1.5 truncate text-[12px] font-semibold text-[#426076]">{shipment.origin}</p><p className="mt-0.5 flex items-center gap-1 truncate text-[11px] text-[#71879a]"><MapPin size={11} />{shipment.destination}</p></div><div className="min-w-0"><div className="flex items-center justify-between gap-3"><p className="label-kicker">Lifecycle</p><p className={`text-[10px] font-bold ${shipment.delay.includes("later") ? "text-[#a96810]" : "text-[#16803c]"}`}>{shipment.delay}</p></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#e6eff4]"><div className={`h-full rounded-full ${shipment.status === "Delivered" ? "bg-[#16803c]" : shipment.delay.includes("later") ? "bg-[#b7791f]" : "bg-[#1769aa]"}`} style={{ width: `${shipment.progress}%` }} /></div><p className="mt-1.5 text-[11px] font-medium text-[#64748b]">ETA: {shipment.eta}</p></div><span className="hidden rounded-md border border-[#dce8f0] p-2 text-[#1769aa] group-hover:bg-[#eaf5fc] sm:grid"><Route size={15} /></span></button>)}</div></section>
    <DetailDrawer open={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.trackingNumber ?? "Shipment detail"} subtitle={selected ? `${selected.drug} · ${selected.quantity}` : undefined}>{selected && <div className="space-y-6"><section className="overflow-hidden rounded-lg border border-[#c7dce9] bg-[#0b3659] text-white"><img src="/manus-storage/distrack-shipment-route_53ac9077.jpg" alt="Medical delivery route" className="h-[150px] w-full object-cover opacity-75" /><div className="-mt-14 relative bg-gradient-to-b from-transparent via-[#0b3659]/80 to-[#0b3659] px-4 pb-4 pt-10"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-sky-200">Current route</p><p className="mt-1 text-sm font-bold">{selected.origin} → {selected.destination}</p></div><StatusBadge status={shipmentTone(selected.status)} label={selected.status} /></div></div></section><section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[{ label: "Supply order", value: selected.supplyOrder }, { label: "Quantity", value: selected.quantity }, { label: "ETA", value: selected.eta }, { label: "Route status", value: selected.delay }].map((item) => <div key={item.label} className="rounded-md border border-[#dce8f0] bg-white p-3"><p className="label-kicker">{item.label}</p><p className="mt-2 text-[12px] font-bold leading-5 text-[#102a43]">{item.value}</p></div>)}</section><section><SectionHeading label="Shipment timeline" title="Six-stage route lifecycle" detail="Recorded operational events and expected hand-offs." /><div className="mt-5"><ShipmentTimeline events={selected.events} /></div></section>{selected.status === "Delivered" && <div className="flex justify-end"><button onClick={() => void receive(selected)} className="inline-flex h-10 items-center gap-2 rounded-md bg-[#1769aa] px-3.5 text-xs font-bold text-white hover:bg-[#0f5d9f]"><PackageCheck size={15} />Confirm receipt</button></div>}</div>}</DetailDrawer>
  </div>;
}
